version: v2

global:
  variables:
  - SONAR_HOST_URL=http://0.0.0.0:9000
  runner:
    os_image: ubuntu
    containers:
    - image: docker.io/bitnami/postgresql:16
      environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=sonarqube
      - POSTGRESQL_DATABASE=sonarqube
    - image: bitnami/sonarqube:10.7.0
      environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_DATABASE_HOST=0.0.0.0
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=sonarqube
      - SONARQUBE_DATABASE_NAME=sonarqube

tasks:
  download:
    steps:
    - checkout
    - cache/pull: mvn-sonarqube-{{ checksum "pom.xml" }}
    
    - commands:
      - sudo sysctl vm.max_map_count
      - sudo sysctl vm.max_map_count=262144
      - dockerize -wait tcp://0.0.0.0:9000 -timeout 10m
      - mvn verify sonar:sonar -Pcoverage

    # print log of services if anything fails
    - commands:
      - docker logs postgresql
      - docker logs sonarqube
      when: on_fail
  
    - cache/push:
        key: mvn-sonarqube-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
        - ~/.sonar/cache
    
    - reports/html: target/site/jacoco
    - reports/junit: target/surefire-reports/*.xml

